### ISSUE TITLE
Comment before function declaration causes error 

### ISSUE THREAD

**Issue by bsweileh** [noxdafox/iclips#8] opened 2022-03-13 20:29 UTC
Hi,

When I place a comment before a function declaration in iCLIPS, I get the message:

> [EXPRNPSR3] Missing function declaration for '[put the name of your function here]'.

Attached is a screenshot showing a commented defrule (taken from Giarratano and Riley's "Expert Systems: Principles and Programming", 4th Edition).

It seems that the comment is only causing an issue before the function definition and not inside it.

Please advise. Thanks.

![2022-03-13_14-28-08](https://user-images.githubusercontent.com/42196212/158077966-943ceb33-dd1e-4424-ab45-3df603c5c8fd.jpg)

**Comment by noxdafox** [comment] 2022-06-28 17:07
This is a duplicate of #4.

**Closed as completed by noxdafox** 2022-06-28 17:07 UTC
Labels: duplicate
